### ISSUE TITLE
How to use Windows and a specific version of R?

### ISSUE THREAD

**Issue by erossini** [jamiegaida/AzurePipelineR#4]
Hi,
thank you for this pipeline. It is working very well!

I have a question about the environment. The pipeline is using `rocker/tidyverse:latest` based on Linux. Do you have an idea if I can replace this image with one based on Windows?

The problem I'm facing is my `R` developers are using Windows to create the `R` scripts and some dependencies are slightly different in Windows and Linux or they drag different versions of the same libraries.

Also, is it possible to define what version of `R` I want to use?

I have a workflow in GitHub that is working but I want to migrate everything on Azure DevOps. This workflow is quite compact and easy to use.

    # Workflow derived from https://github.com/r-lib/actions/tree/master/examples
    # Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
    on:
      pull_request:
        branches: [main, master, dev]

    name: RCheck

    jobs:
      RCheck:
        runs-on: ${{ matrix.config.os }}

        name: ${{ matrix.config.os }} (${{ matrix.config.r }})

        strategy:
          # We keep a matrix for convenience, but we would typically just run on one
          # single OS and R version, aligned with the target deployment environment
          matrix:
            config:
              - {os: windows-latest, r: '3.6.3'}
              # - {os: windows-latest, r: 'latest'}

        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          R_KEEP_PKG_SOURCE: yes

        steps:
          - name: Check out Github repo
            uses: actions/checkout@v2

          - name: Install Pandoc
            uses: r-lib/actions/setup-pandoc@v2

          - name: Install R
            uses: r-lib/actions/setup-r@v2
            with:
              r-version: ${{ matrix.config.r }}
              use-public-rspm: true

          - name: Install R Dependencies
            uses: r-lib/actions/setup-r-dependencies@v2
            with:
              extra-packages: |
                any::rcmdcheck
              needs: check

          - name: Check R Package
            uses: r-lib/actions/check-r-package@v2
            with:
              args: 'c("--no-manual", "--as-cran", "--no-multiarch")'
              error-on: '"error"'
              check-dir: '"check"'
              upload-snapshots: true

Thank you in advance.
Enrico

**Comment by jamiegaida** [comment]
Hi Enrico,
Thanks for your query!
This pipeline deliberately uses a linux based image to keep things as simple as possible. It is definitely possible to run on a windows image. Have a look at this for a starting point: https://github.com/r-lib/r-azure-pipelines/blob/master/azure-tidyverse.yml
Best of luck with your efforts
Jamie
